name: JiroTravelersMap
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13.2
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: QQ9QE2K9VN
packages:
  Danger:
    url: https://github.com/danger/swift.git
    from: 3.0.0
  Rswift:
    url: https://github.com/mac-cain13/R.swift.Library.git
    from: 5.1.0
targets:
  JiroTravelersMap:
    type: application
    platform: iOS
    sources: 
      - JiroTravelersMap
      - path: Libs/R.generated.swift
        optional: true
        createIntermediateGroups: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.room417.JiroTravelersMap
      config:
        debug:
          CODE_SIGN_STYLE: Automatic
          ENABLE_PREVIEWS: true
          DEVELOPMENT_ASSET_PATHS: JiroTravelersMap/Resources/Preview Content
    info:
      path: JiroTravelersMap/Resources/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIRequiredDeviceCapabilities:
          - armv7
        UIStatusBarTintParameters:
          UINavigationBar:
            Style: UIBarStyleDefault
            Translucent: false
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    entitlements:
      path: JiroTravelersMap/Resources/JiroTravelersMap.entitlements
      properties: []
        # com.apple.security.application-groups: group.jp.room417.JiroTravelersMap
    dependencies:
      - package: Rswift
    preBuildScripts:
      - name: Swiftlint
        script: mint run swiftlint
      - name: R.swift
        script: |
          if mint list | grep -q 'R.swift'; then
            mint run R.swift rswift generate "$SRCROOT/Libs/R.generated.swift"
          else
            echo "error: R.swift not installed; run 'mint bootstrap' to install"
            return -1
          fi
        inputFiles: [$TEMP_DIR/rswift-lastrun]
        outputFiles: [$SRCROOT/Libs/R.generated.swift]
  JiroTravelersMapTests:
    type: bundle.unit-test
    platform: iOS
    sources: JiroTravelersMapTests
    settings:
      INFOPLIST_FILE: JiroTravelersMapTests/Supporting Files/info.plist
      CODE_SIGN_STYLE: Automatic
      TEST_HOST: ${BUILT_PRODUCTS_DIR}/JiroTravelersMap.framework

